/**
 * @file unconfig.h
 *
 * Autoconf defines of apache are conflicting with autoconf defines of
 * out package. Therefore this file, which undefines all PACKAGE_* defines,
 * is included before config.h which is automatically generated by autoconf.
 */

#ifndef UNCONFIG_H
#define UNCONFIG_H

#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION

#endif
